### ISSUE TITLE
RubySG website redesign

### ISSUE THREAD

**Issue by sarupbanskota** [rubysg/rubysg-reboot#103]
Hi folks, 

Not sure how welcome this proposal would be, but as a means to train myself better with visual design stuff, I have been tinkering with a concept for RubySG's website.

Here's a mobile version:

![rubysg-mobile](https://cloud.githubusercontent.com/assets/3149580/14249764/e4c9a30a-faad-11e5-8550-31b88e6fbaf7.jpg)

Here's a tablet one in portrait mode (could use feedback):

![rubysg-tablet](https://cloud.githubusercontent.com/assets/3149580/14249765/e52663f6-faad-11e5-8b07-1c604474eb55.jpg)

Love? Hate? Comments?

Notes: 
1. Writing isn't my forte, so the text on the mockups is completely representative
2. To give myself direction, I picked my favourite logo from https://github.com/rubysg/rubysg-reboot/issues/98, and decided to work with it. Ofc, depending on which logo makes it, I can adapt my design
3. I stole the images from links I got to from RubySG's meet up page - while I'm not posting them here, I have them saved for attribution.

**Comment by tgxworld** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by Drenmi** [comment]
Proposals are always welcome! :grinning:

Let me offer some feedback:

---

Firstly: love the header. Super clean. :rocket: 

---

Secondly: the middle part looks a bit over saturated, with the full bleed images and the heavy colour. Maybe you can experiment with tinting or overlaying the images?

---

Most importantly: not all mobile devices are ginormous. :sweat_smile: I'm thinking how this would look on my iPhone 5c, and I can already feel how tiny those buttons are. In my humble opinion, going for two columns on mobile is too ambitious.

Reading
sentences with
only two or
three words
per line can
get pretty
annoying. :wink:

---

Finally: the footer looks almost as awesome as the header, but I think maybe you went a bit overboard with the custom shape for the invite request. Not sure if it's a button or a text field, or why it has that odd shape. :smile:

---

Thanks for wanting to put your time into this. I'm sure this can serve as a great start. (Not that I am making any of the decisions about the website. :grimacing: )

**Comment by winston** [comment]
Actually.. we stopped doing RailsGirls this year and TradeGecko doesn't seem to be doing Ruby Tea Party anymore too. :)

**Comment by sarupbanskota** [comment]
I'm listening, and will pick this up again this week when I a significant set of changes :-)

@winston, that leaves us with just the Ruby weekly/monthly meetup, correct? I have been terrible with attending meet ups in Singapore (and in general this year), so I'm sorry about the ignorance!

If we're going to remove the other two meet ups, how about I move the section about company list and SG guide into the meet up boxes?

@Drenmi As for the meet up boxes themselves, completely agree about it being too colour heavy; I'll experiment with tinting images.

I didn't want the tiny buttons myself - my intention was to leave the entire red box clickable. Without the button, it would be difficult to convey _you can click this_. I'll do an iteration with the buttons removed and with an arrow next to the text. 

Thanks for the feedback!

**Comment by jsyeo** [comment]
Nice! Looks good but I have a couple of nitpicks and comments:

* The request invite button looks odd. Would be great if it is consistent with the other buttons on the page.
* The color theme doesn't match the color of the logo.

**Comment by winston** [comment]
> If we're going to remove the other two meet ups, how about I move the section about company list and SG guide into the meet up boxes?

Sure you can try that.

I also prefer the use of standard web form input fields. :)

**Comment by sarupbanskota** [comment]
Alright, WIP:

1. Changed logo to reflect the winner from https://github.com/rubysg/rubysg-reboot/issues/98
2. Changed primary colour to the dark one from the logo
3. Removed the two meetups, and moved the company listing and guide into the middle section
4. Tried to make the middle section less colourful - removed buttons and replaced them with  a completely clickable area
5. Moved to slack logo into the button for better aligning, and removed the odd shape

This leaves me with some space below the middle section. Any tips on what could go in there?

I'll attempt to code this (and another card idea I have time permitting) .. unless somebody wants to volunteer!

![mobile portrait](https://cloud.githubusercontent.com/assets/3149580/14940557/5dbcca76-0fad-11e6-975f-a2a8e9ec59a1.jpg)

Feedback!

**Comment by yangshun** [comment]
Sorry @sarupbanskota  I don't have the svg version yet. Will try to come up with one and send it to you. I'm also working on a redesign of the website. Let's exchange opinions then (:

**Comment by jhecking** [comment]
@sarupbanskota, I like the new design. Nice and clean! Maybe you can add a link to reddotrubconf.com?

**Comment by sarupbanskota** [comment]
@jhecking noted. 

---

I'm also thinking of a "our friends" section, and linking to some of the other open source communities of interest. What do you think, everyone?

**Comment by winston** [comment]
I have been hoping to incorporate this somehow. https://github.com/rubysg/rubysg-reboot/issues/2

**Comment by Drenmi** [comment]
Closing this now, as the new design has been up for a while, and there hasn't been any activity. Feel free to open a new issue for specific suggestions. And thanks again @sarupbanskota. 🙇
