### ISSUE TITLE
Social Media Cards

### ISSUE THREAD

**Issue by winston** [rubysg/rubysg-reboot#123]
Wanted to post about the new design on facebook, and the card showed up as:

![screen shot 2016-06-20 at 10 58 10 pm](https://cloud.githubusercontent.com/assets/2112/16199002/97ce37b8-373a-11e6-8b90-8d9c27f0e59d.png)

Any plans to update that @yangshun? 😄

**Comment by yangshun** [comment]
Whoops give me a moment I'll work on that

**Comment by winston** [comment]
No hurry. :)

**Comment by yangshun** [comment]
Ok just cleared FB's cache for the page via sharing debugger: https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fruby.sg

**Comment by winston** [comment]
Thank you @yangshun!
