### ISSUE TITLE
Upgrade Heroku stack - requires fixing font-awesome issues

### ISSUE THREAD

**Issue by hanmd82** [rubysg/rubysg-reboot#260]
From https://devcenter.heroku.com/articles/cedar-14-stack

```
Cedar-14 stack is deprecated and will reach its end of life in April 2019. We strongly recommend that you upgrade your apps to Heroku-16.
```
The production app for this repo is running on `cedar-14` stack, which will be deprecated in 2019.

The staging app is running on `heroku-16` stack, but the `font-awsome` icons are not showing properly. This needs to be fixed before the production app is [migrated](https://devcenter.heroku.com/articles/heroku-16-stack) to `heroku-16` stack

 https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by valentine** [comment]
I saw @Drenmi just mention this issue on the Telegram group.

Forked the repo and deployed it to [my own Heroku site](https://v-rubysg.herokuapp.com/), on both `heroku-18` and `heroku-16` stacks. It seems to be fine.

**Comment by Drenmi** [comment]
@valentine Interesting. Let me try to upgrade our staging dyno to `heroku-18` and redeploy.

**Comment by kevinhq** [comment]
Will try on heroku too. Perhaps this will fix it https://github.com/heroku/rails_12factor

**Comment by kevinhq** [comment]
deployed this on https://rubysg-reboot.herokuapp.com/

With those heroku config vars:
```
LANG:                     en_US.UTF-8
RACK_ENV:                 production
RAILS_ENV:                production
RAILS_LOG_TO_STDOUT:      enabled
RAILS_SERVE_STATIC_FILES: enabled
```

font awesome icon is loaded properly on chrome.

**Comment by Drenmi** [comment]
>  https://github.com/heroku/rails_12factor

This hasn't been required since Rails 4, IIRC.

**Comment by kevinhq** [comment]
> > https://github.com/heroku/rails_12factor
> 
> This hasn't been required since Rails 4, IIRC.

correct. It turns out I can't reproduce the issue.
