### ISSUE TITLE
Evaluate possibility of removing Postgres and pg gem

### ISSUE THREAD

**Issue by hanmd82** [rubysg/rubysg-reboot#261]
In this app, we do not use ActiveRecord. Hence there may not be a real need for PostgreSQL - we simply include ActiveModel to parse a `companies.yml` file

To evaluate whether/how to remove any dependency on Postgres and the `pg` gem

**Comment by kevinhq** [comment]
It will get errors unless we remove activerecord gem as well (but not sure if Rails can run without activerecord)

**Comment by TayKangSheng** [comment]
I'm using postgres for RubySGBot and collect feedback so this issue is not relevant anymore. 
https://github.com/rubysg/rubysg-reboot/pull/303
https://github.com/rubysg/rubysg-reboot/pull/338
