### ISSUE TITLE
Discuss how to update companies.yml

### ISSUE THREAD

**Issue by hanmd82** [rubysg/rubysg-reboot#288]
see #287

> email them and if email bounce or no reply then delete?
Tried this before - got close to 0% response. We can try again.

To make it easier to update the list, we already know some companies active (in terms of supporting meetups and updating this repo) since 2018 - recorded [here](https://github.com/rubysg/rubysg-reboot/wiki/Companies-contributing-to-RubySG-community). 

We can update this list with companies that supported meetups in 2019.

---

Another related issue is how to define and update `contribution_count`, i.e. contributions since when? What weights should we use? 

This ties in to how we want companies to be listed - is there a need for a 'ranking' system, or should we do away with that altogether? What behavior would we like to incentivise, towards encouraging more community involvement and events?

**Comment by winston** [comment]
My suggestion is this:
- do one round of cleanups
- add a updated_at field to companies.yml
- listings will only show companies who have bumped their updated_at in the last 6 months
- or we can just push companies that have not been updated in the last 6 months to a section called archive or something down in the page 

Con is I am not sure if companies will bother to bump their updated_at every 6 months or not. 

As for contribution count, MD put it aptly as the "active" company indicator. That's how I see it now.  I think it's still good to recognize company with active contributions, but maybe should reset to every year? (So maybe we need to keep an array of contribution dates)

Wdyt?

**Comment by TayKangSheng** [comment]
Did a clean up of the `/companies` page here. Can reopen this issue if we need another round of effort to clean things up. 
https://github.com/rubysg/rubysg-reboot/pull/335
