### ISSUE TITLE
Should relax rails version restriction

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/rubysg-reboot#300]
Instead of `'~> 5.0.7.1'`, maybe we should do `'~> 5'` so that we are not too far back from edge.

**Comment by Drenmi** [comment]
Considering how simple the app is, I would say we should just shoot straight for `~> 6`. That will give us some runway. Or we'll need to upgrade pretty soon again. 😬

**Comment by kevinhq** [comment]
+1  for Rails 6.
