### ISSUE TITLE
travis PR status never comes back

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/rubysg-reboot#305]
> “continuous-integration/travis-ci” is deprecated.

https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

<img width="694" alt="Screenshot 2020-06-10 at 10 43 36 PM" src="https://user-images.githubusercontent.com/10722197/84282095-edeffd80-ab6b-11ea-9df4-c99ba7ecf66d.png">

**Comment by weimeng** [comment]
Any interest in using GitHub Actions instead? I've recently set up a Rails project to work with Actions, I can just port that over easily if this is just for running tests (I don't see any linters).

**Comment by TayKangSheng** [comment]
@weimeng sure. i'm all for it! go ahead 😀

**Comment by TayKangSheng** [comment]
Travis has been removed in https://github.com/rubysg/rubysg-reboot/pull/337
