### ISSUE TITLE
outdated brochure

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/rubysg-reboot#318]
the content on ruby.sg landing page is outdated.

1. Ruby meetup is every 3rd thursday.
2. Telegram QR code and link is broken.

**Comment by adriangohjw** [comment]
Ruby meetup copyrighting and telegram QR code already fixed, only thing broken is telegram link - made a PR at https://github.com/rubysg/rubysg-reboot/pull/330

**Comment by adriangohjw** [comment]
Issue seems to be fixed
