### ISSUE TITLE
Alphabetically unbiased companies page

### ISSUE THREAD

**Issue by Drenmi** [rubysg/rubysg-reboot#56]
Since this discussion was brought up during the latest meet up:

Should we shuffle the entries in the companies page, to remove "unfairness" for the more "alphabetically challenged" companies? :grimacing:

I think it's a good idea. In the spirit of Ruby. :wink:

Expanding on the idea, we could put the companies into two groups: "hiring" and "not hiring". So we split, shuffle both groups, display "hiring" companies first (in random order) and "not hiring" companies following (in random order.)

Thoughts?

:kissing_heart:

**Comment by winston** [comment]
I actually think alphabetical is fair and offers the most consistent user experience to a first time user. 

Imagining myself as a first time user who visits ruby.sg/companies and all the companies are randomized, then I might think that the sorting is screwed up.. or why can't someone just implement an alphabetical sort.. Only if I refresh the page a few times, maybe then I'll get the point the "oh.. it's random.. but can I still sort it?". So maybe then we can put in a message at the top that says "This page is randomized". Is it nice?

If we have enough folks who prefer random sort, then let's do it. But I would think we shouldn't split the companies into "hiring" and "not hiring", and give "hiring" companies priority. That's removing the "fairness" out of "random". :)

**Comment by arnvald** [comment]
I agree with Winston here. If I go to that page to just browse, then I don't care about the order, but if I'm going there to check some particular company, then finding it with randomized order (changing every time) is hard and user experience is pretty bad.

About hiring/not hiring, maybe let's add a "hiring only" checkbox that will filter companies?

**Comment by Drenmi** [comment]
Agree with @arnvald that for browsing it doesn't matter, but for parsing random would be annoying.

Personally I don't mind the way it is now. (I have a mild OCD with a penchant for ordered lists. :stuck_out_tongue: )

**Comment by winston** [comment]
> About hiring/not hiring, maybe let's add a "hiring only" checkbox that will filter companies?

That may work.

**Comment by Drenmi** [comment]
Closing this in favour of https://github.com/rubysg/rubysg-reboot/issues/66 :smiley:
