### ISSUE TITLE
Companies page to indicate talks

### ISSUE THREAD

**Issue by winston** [rubysg/rubysg-reboot#66]
Ref: https://www.facebook.com/groups/singaporerubybrigade/permalink/685462351590975/

> Maybe one of the prerequisite for putting up a logo on ruby.sg/companies in the future is that someone from the company must do a talk at a Ruby meetup to prove that the company has legit Ruby users.
>
> And we'll also indicate on the same page that the company has spoken at Ruby meetup before.
>
> People often ask me how to attract developers to their companies...
>
> Personally, knowing that the company has good people who can either present their knowledge at public settings (probably means he/she has something to teach me in day to day work as well), or encourages their developers to share their learnings outside of the normal daily grind would be two items on my checklist. Thoughts?

A part of this is also to prevent the ruby.sg/companies page from becoming just a "recruitment" page.

And we also have a discussion on "sorting" in #56. I would also suggest using this as one of the "sort", where we have two sections on the ruby.sg/companies page. First, above the fold section for companies who have given talks (at least 2?) / participated actively in ruby meetups (sorted alphabetically), and the section below for companies who have yet done a talk.

End goal is to foster a learning community.

**Comment by winston** [comment]
@Drenmi @hanmd82 @sarupbanskota @jhecking @marcosbeirigo @davidchua @teohm @zamakkat @yarbelk @cykhoo @weiqingtoh @gherry @cheeaun @allenlsy @rlhh @tohyongcheng @jameshuynh @coffeesam @gabehollombe @raphaeltanyw @stania1 @natnebuer @amgencjana @stevenyap @brega @bheavens @sayanee @ascendbruce @fmsurvey @arnvald 

CC-ing everyone who has contributed a logo to ruby.sg/companies page. Thanks!

**Comment by yangshun** [comment]
:+1: great idea!

**Comment by JuanitoFatas** [comment]
> CC-ing everyone who has contributed a logo to ruby.sg/companies page. Thanks!

Can create teams then use [team mentions](https://github.com/blog/1121-introducing-team-mentions). :blush:

**Comment by jsyeo** [comment]
:+1:

**Comment by Drenmi** [comment]
I am not averse to the idea of sectioning companies into contributors and non-contributors. :+1:

> A part of this is also to prevent the ruby.sg/companies page from becoming just a "recruitment" page.

So do we need a discussion on what kind of page we want it to be instead? :smiley:

**Comment by winston** [comment]
> So do we need a discussion on what kind of page we want it to be instead?

My intention was for the page to be a showcase of companies in Singapore who uses and supports Ruby. "Hey Ruby is still being used by companies!". The "recruitment" links were more for convenience.

**Comment by Drenmi** [comment]
@tgxworld, @winston: I have taken a stab at this in #138. It currently "promotes" companies with two or more talks. I think it could also be fair to give companies one point for sponsoring a meetup.

Need your thoughts on this. 😀

**Comment by winston** [comment]
@Drenmi Nice! Looks good to me. And yes, we can give a point to companies sponsoring too!

**Comment by Drenmi** [comment]
@winston, @tgxworld: Adding one point for each sponsorship (venue or food) ups the count from 4 to 9. (I credited IDA to GDS, and MoE to ESTL.)
