### ISSUE TITLE
Non-hiring companies have "Hiring" bar appearing

### ISSUE THREAD

**Issue by winston** [rubysg/rubysg-reboot#90]
On http://ruby.sg/companies. Probably related to #89.

For example: 
![screen shot 2016-02-23 at 1 35 53 pm](https://cloud.githubusercontent.com/assets/2112/13242690/6a05b6f4-da32-11e5-97ec-afb7ea224a82.png)

Jolly Good Code is not hiring, but hiring link shows up as "ruby.sg/nil".

**Comment by arnvald** [comment]
```
YAML.load("hiring_url: nil")
# => {"hiring_url" => "nil"}
```

The solution is to remove the `hiring_url` key from companies that are not hiring

cc @cykhoo

**Comment by Drenmi** [comment]
You don't need to remove the key, just leave the value blank:

```
YAML.load("hiring_url:")
# => {"hiring_url": nil}
```

**Comment by winston** [comment]
Prefer leaving the value blank, so that the next person knows that there's a hiring_url that can be filled.
