### ISSUE TITLE
Cast your vote for RubySG logotype!

### ISSUE THREAD

**Issue by Drenmi** [rubysg/rubysg-reboot#98]
In https://github.com/rubysg/rubysg-reboot/issues/1, we asked the community to contribute suggestions for the RubySG logotype, and we received some awesome responses from @stevenyap, @ariffmunshi, @jessicateh, and @yangshun.

We have shortlisted some of these suggestions, and now we need your help in voting! The shortlisted options are posted as replies below, and you can cast your vote by using the "reaction" feature in GitHub to add a :+1:.

Here's a screenshot if you can't find it:

<img width="287" alt="screen shot 2016-03-14 at 17 56 59" src="https://cloud.githubusercontent.com/assets/5259935/13741036/e0cfc31a-ea0e-11e5-9019-a0446372c215.png">

(Note that only :+1: reactions will be counted.)

Voting will be open until the end of the month.

:grinning:

**Comment by Drenmi** [comment]
![logo1](https://cloud.githubusercontent.com/assets/5259935/13741257/4aac208e-ea10-11e5-803d-e1221e8340f8.gif)

**Comment by Drenmi** [comment]
![logo2](https://cloud.githubusercontent.com/assets/5259935/13741261/5390289e-ea10-11e5-8d79-b645d2579366.gif)

**Comment by Drenmi** [comment]
![logo3](https://cloud.githubusercontent.com/assets/5259935/13741266/59f45a5c-ea10-11e5-90dd-25fe74d83f10.png)

**Comment by Drenmi** [comment]
![logo4](https://cloud.githubusercontent.com/assets/5259935/13741273/6157d4a4-ea10-11e5-88af-946863ebf296.png)

**Comment by Drenmi** [comment]
![logo5](https://cloud.githubusercontent.com/assets/5259935/13741277/6625bc80-ea10-11e5-8d0a-43640895529c.png)

**Comment by Drenmi** [comment]
![logo6](https://cloud.githubusercontent.com/assets/5259935/13741285/6d797350-ea10-11e5-8544-0db12ef09fcc.png)

**Comment by Learnemy** [comment]
Why isn't 😘 an option?

**Comment by winston** [comment]
@Drenmi We have a winner? :)

**Comment by Drenmi** [comment]
And the winner is:

![Winner!](https://cloud.githubusercontent.com/assets/5259935/13741277/6625bc80-ea10-11e5-8d0a-43640895529c.png)

by @yangshun!

:tada: :tada: :tada:

**Comment by yangshun** [comment]
Thanks! What are my next steps? (:

**Comment by winston** [comment]
@yangshun Can we do something like https://github.com/webuildsg/branding? :)

**Comment by sarupbanskota** [comment]
@yangshun congrats on the logo! would you have an SVG that I can use on the RubySG website I'm designing? https://github.com/rubysg/rubysg-reboot/issues/103

**Comment by winston** [comment]
@yangshun @tgxworld Do we have an upload of the logos to a repo? i.e. branding? I thought we did it somewhere?
